import next from '../../img/next.png'
const Workcat= [
    {
        id:1,
        title:'Next js',
        subtit: "Node js",
        category: "popular",
        icon: next,
    },
    {
        id:2,
        title:'Next js',
        subtit: "Node js",
        category: "frontend",
        icon: next,
    },
    {
        id:3,
        title:'Next js',
        subtit: "Node js",
        category: "backend",
        icon: next,
    },
    {
        id:4,
        title:'Next js',
        subtit: "Node js",
        category: "vite",
        icon: next,
    },
    {
        id:5,
        title:'Next js',
        subtit: "Node js",
        category: "creative",
        icon: next,
    },
    {
        id:6,
        title:'Next js',
        subtit: "Node js",
        category: "vanila",
        icon: next,
    },
    {
        id:7,
        title:'Next js',
        subtit: "Node js",
        category: "popular",
        icon: next,
    },
    {
        id:8,
        title:'Next js',
        subtit: "Node js",
        category: "vanila",
        icon: next,
    },
    {
        id:9,
        title:'Next js',
        subtit: "Node js",
        category: "frontend",
        icon: next,
    },
    {
        id:10,
        title:'Next js',
        subtit: "Node js",
        category: "backend",
        icon: next,
    },
    {
        id:11,
        title:'Next js',
        subtit: "Node js",
        category: "creative",
        icon: next,
    },
    {
        id:12,
        title:'Next js',
        subtit: "Node js",
        category: "design",
        icon: next,
    },
    {
        id:13,
        title:'Next js',
        subtit: "Node js",
        category: "creative",
        icon: next,
    },
    {
        id:14,
        title:'Next js',
        subtit: "Node js",
        category: "popular",
        icon: next,
    },
    {
        id:15,
        title:'Next js',
        subtit: "Node js",
        category: "backend",
        icon: next,
    },
    {
        id:16,
        title:'Next js',
        subtit: "Node js",
        category: "frontend",
        icon: next,
    },
    {
        id:17,
        title:'Next js',
        subtit: "Node js",
        category: "design",
        icon: next,
    },
    {
        id:18,
        title:'Next js',
        subtit: "Node js",
        category: "design",
        icon: next,
    },
    {
        id:19,
        title:'Next js',
        subtit: "Node js",
        category: "popular",
        icon: next,
    },
    {
        id:20,
        title:'Next js',
        subtit: "Node js",
        category: "popular",
        icon: next,
    },
    {
        id:21,
        title:'Next js',
        subtit: "Node js",
        category: "backend",
        icon: next,
    },
    {
        id:22,
        title:'Next js',
        subtit: "Node js",
        category: "design",
        icon: next,
    },

]
export default Workcat;